module.exports = Object.freeze({
    RSVP_FORM_NEW_MODE: 'NEW_RSVP',
    RSVP_FORM_EDIT_MODE: 'EDIT_RSVP',
    CATEGORY_FORM_NEW_MODE: 'NEW_CATEGORY',
    CATEGORY_FORM_EDIT_MODE: 'EDIT_CATEGORY',
    INVITATION_FORM_NEW_MODE: 'NEW_INVITATION',
    INVITATION_FORM_EDIT_MODE: 'EDIT_INVITATION',
    INVITATION_MAX_GUESTS: 10,
    INVITATION_STATUS_NOT_SENT: 'NS',
    INVITATION_STATUS_SENT: 'ST',
    INVITATION_STATUS_REPLIED_ATTENDING: 'RA',
    INVITATION_STATUS_REPLIED_NOT_ATTENDING: 'RN',
    INVITATION_STATUS_LOOKUP: {
        'NS': 'Not Sent',
        'ST': 'Sent',
        'RA': 'Replied Attending',
        'RN': 'Replied Not Attending'
    }
});
